version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile-gcp
    ports:
      - "8000:8000"
    command: "./start.sh"
    environment: 
      - API_BASE_URL="http://localhost:5000"
      - RDATA_BASE_URL="http://localhost:7000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/cfb/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
