version: "3.8"
services:
  python:
    build: 
      context: .
      dockerfile: python/Dockerfile
    expose:
      - 8080
    volumes: 
      - ./python/models:/models
  node:
    build: 
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5000:5000"
    links:
      - python