version: "3.8"
services:
  python:
    build: 
      context: .
      dockerfile: python/Dockerfile
    expose:
      - 8080
    volumes: 
      - ./python/models:/models
  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5000:5000"
    expose:
      - 5000
    links:
      - python
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8000:8000"
    links:
      - api