version: "3.8"
services:
  python:
    build: 
      context: ./python
      dockerfile: Dockerfile
    expose:
      - 7000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - ROOT_IP=0.0.0.0
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - 5000
    links:
      - python
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/cfb/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - python
    environment:
      - RDATA_BASE_URL=http://python:7000
      - NODE_DEBUG=[api]
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    links:
      - api
    depends_on:
      - api
      - python
    environment:
      - API_BASE_URL=http://api:5000
      - NODE_DEBUG=[frontend]