version: "3.8"
services:
  rdata:
    build: 
      context: .
      dockerfile: rdata/Dockerfile
    expose:
      - 7000
    volumes: 
      - ./rdata/models:/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
  python:
    build: 
      context: .
      dockerfile: python/Dockerfile
    expose:
      - 8080
    volumes: 
      - ./python/models:/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5000:5000"
    expose:
      - 5000
    links:
      - python
      - rdata
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/cfb/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8000:8000"
    links:
      - api